name: "Stage deploy"

on:
  push:
    branches:
      - master

jobs:
  stage:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      id-token: write
      pull-requests: write
    steps:
      - name: "Checkout"
        uses: actions/checkout@v3

      - name: "Set git commit short hash"
        id: vars
        run: echo "::set-output name=sha_short::$(git rev-parse --short HEAD)"

      - name: "Build Docker image"
        run: npm run deploy
